services:
  - type: web
    name: viral-backend
    env: python
    pythonVersion: "3.11.0"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
